--SELECIONANDO BANCO
USE MeuRH;

GO

--CRIANDO A TABELA
CREATE TABLE DEP_DEPARTAMENTOS(
	DEP_ID INT IDENTITY(1, 1) PRIMARY KEY,
	DEP_NOME VARCHAR(50) NOT NULL,
);

GO

--INSERINDO DADOS
INSERT INTO DEP_DEPARTAMENTOS 
(DEP_NOME) VALUES
('RECURSOS HUMANOS'),
('TECNOLOGIA DA INFORMAÇÃO'),
('CONTROLADORIA');

--SELECIONANDO OS DADOS DA TABELA
SELECT * FROM DEP_DEPARTAMENTOS;

--ALTERANDO A TABELA DE FUNCIONARIOS PARA ADD O CAMPO DO DEPARTAMENTO
ALTER TABLE FUN_FUNCIONARIOS 
	ADD DEP_ID INT NOT NULL DEFAULT 1;

--SELECIONANDO TABELA
DEP_
--ADICIONANDO UMA CHAVE ESTRAGEIRA
ALTER TABLE FUN_FUNCIONARIOS
	ADD CONSTRAINT FK_FUN_FUNCIONARIOS__DEP_DEPARTAMENTOS__DEP_ID 
	FOREIGN KEY (DEP_ID) REFERENCES DEP_DEPARTAMENTOS(DEP_ID);

--ATUALIZANDO O DEPARTAMENTO
UPDATE FUN_FUNCIONARIOS SET DEP_ID = 2 WHERE FUN_ID = 4;
UPDATE FUN_FUNCIONARIOS SET DEP_ID = 3 WHERE FUN_ID = 5;

--ADICIONANDO COLUNA DE RESPONSAVEL DO SETOR
ALTER TABLE DEP_DEPARTAMENTOS
	ADD FUN_ID_RESPONSAVEL INT NOT NULL DEFAULT 1;

--SELECIONANDO DEPARTAMENTOS
SELECT * FROM DEP_DEPARTAMENTOS;

--ADICIONANDO UMA CHAVE ESTRAGEIRA
ALTER TABLE DEP_DEPARTAMENTOS
	ADD CONSTRAINT FK_DEP_DEPARTAMENTOS__FUN_FUNCIONARIOS_FUN_ID 
	FOREIGN KEY (FUN_ID_RESPONSAVEL) REFERENCES FUN_FUNCIONARIOS (FUN_ID);

DEP
SELECT * FROM PAC_PONTOS_ACESSOS;

--ATUALIZANDO O ID RESPONSAVEL PELO SETOR
UPDATE DEP_DEPARTAMENTOS SET FUN_ID_RESPONSAVEL = 4 WHERE DEP_ID = 2;
UPDATE DEP_DEPARTAMENTOS SET FUN_ID_RESPONSAVEL = 5 WHERE DEP_ID = 3;

--FAZENDO CONSULTA
SELECT DEP.DEP_NOME AS DEPARTAMENTO,
	CONCAT(FUN2.FUN_SOBRENOME, ', ', FUN2.FUN_NOME) AS [RESPONSAVEL DO DEPARTAMENTO],
	CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS FUNCIONARIO,
	PAC.PAC_DATA_INICIAL,
	PAC.PAC_DATA_FINAL,
	CONVERT(time(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS
FROM FUN_FUNCIONARIOS FUN
LEFT JOIN PAC_PONTOS_ACESSOS  PAC
	ON FUN.FUN_ID = PAC.FUN_ID
INNER JOIN DEP_DEPARTAMENTOS  DEP
	ON FUN.DEP_ID = DEP.DEP_ID
INNER JOIN FUN_FUNCIONARIOS  FUN2
	ON DEP.FUN_ID_RESPONSAVEL  = FUN2.FUN_ID;