--SELECIONANDO O BANCO
USE MeuRH;

GO

--SELECIONANDO A TABELA FUNCIONÁRIOS
SELECT * FROM FUN_FUNCIONARIOS;

--CRIANDO TABELA DE PONTOS DE ACESSOS
CREATE TABLE PAC_PONTOS_ACESSOS
(
	PAC_ID INT IDENTITY(1,1) PRIMARY KEY,
	PAC_DATA_INICIAL DATETIME NOT NULL,
	PAC_DATA_FINAL DATETIME NULL,
	FUN_ID INT NOT NULL
);

--SELECIONANDO NOVA TABELA
SELECT * FROM PAC_PONTOS_ACESSOS;

--CRIANDO CHAVE ESTRANGEIRA ENTRE TABELA FUNCIONARIO E PONTOS DE ACESSOS
ALTER TABLE PAC_PONTOS_ACESSOS
	ADD CONSTRAINT FK_PAC_PONTOS_ACESSOS__FUN_FUNCIONARIOS__FUN_ID
	FOREIGN KEY(FUN_ID)
	REFERENCES FUN_FUNCIONARIOS(FUN_ID);

--INSERINDO DADOS
INSERT INTO PAC_PONTOS_ACESSOS 
(PAC_DATA_INICIAL, FUN_ID) VALUES
('2017-02-01 07:00:00', 1)

--CRIANDO UM CHECK NO CAMPOS DE DATA
ALTER TABLE PAC_PONTOS_ACESSOS
	ADD CONSTRAINT CK_PAC_PONTOS_ACESSOS__DATA_INICIAL_DATA_FINAL
	CHECK 
	(--INSERINDO MAIS PARAMETROS NA REGRA DE NEGÓCIO
		PAC_DATA_INICIAL < PAC_DATA_FINAL AND 
		DATEPART(DAY, PAC_DATA_INICIAL) = DATEPART(DAY, PAC_DATA_FINAL) AND
		DATEPART(MONTH, PAC_DATA_INICIAL) = DATEPART(MONTH, PAC_DATA_FINAL) AND
		DATEPART(YEAR, PAC_DATA_INICIAL) = DATEPART(YEAR, PAC_DATA_FINAL)
	);

--APAGANDO UMA CONSTRAINT
ALTER TABLE PAC_PONTOS_ACESSOS DROP CONSTRAINT CK_PAC_PONTOS_ACESSOS__DATA_INICIAL_DATA_FINAL;

SELECT * FROM PAC_PONTOS_ACESSOS;

--ATUALIZANDO DATA FINAL
UPDATE PAC_PONTOS_ACESSOS SET PAC_DATA_FINAL = '2017-01-02 12:00:00'
WHERE PAC_ID = 1; 

--FAZENDO CALCULOS NAS CONSULTAS
SELECT *, CAST(PAC_DATA_FINAL - PAC_DATA_INICIAL AS time(0)) AS [HORAS TRABALHADAS] FROM PAC_PONTOS_ACESSOS;

--FAZENDO DE OUTRA FORMA
SELECT *, CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS] FROM PAC_PONTOS_ACESSOS;

--fazendo uma bricadeira
SELECT * FROM FUN_FUNCIONARIOS;
SELECT * FROM PAC_PONTOS_ACESSOS;

SELECT FUN_FUNCIONARIOS.FUN_NOME + FUN_FUNCIONARIOS.FUN_SOBRENOME AS [NOME COMPLETO],FUN_FUNCIONARIOS.FUN_DATA_NASCIMENTO, FUN_FUNCIONARIOS.FUN_CPF, CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS] FROM FUN_FUNCIONARIOS, PAC_PONTOS_ACESSOS
WHERE FUN_FUNCIONARIOS.FUN_ID = PAC_PONTOS_ACESSOS.FUN_ID

--OUTRA FORMA
SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO, 
	FUN.FUN_DATA_NASCIMENTO,
	PAC.PAC_DATA_INICIAL,
	PAC.PAC_DATA_FINAL,
	CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS]
FROM FUN_FUNCIONARIOS AS FUN, PAC_PONTOS_ACESSOS AS PAC
WHERE FUN.FUN_ID = PAC.FUN_ID;

--INSERINDO DADOS
INSERT INTO PAC_PONTOS_ACESSOS 
(PAC_DATA_INICIAL, PAC_DATA_FINAL, FUN_ID) VALUES
('2017-02-01 07:03:00', '2017-02-01 11:57:00', 4);

--FAZENDO VIA INNER JOIN
SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO, 
	FUN.FUN_DATA_NASCIMENTO,
	PAC.PAC_DATA_INICIAL,
	PAC.PAC_DATA_FINAL,
	CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS]
FROM FUN_FUNCIONARIOS AS FUN
INNER JOIN PAC_PONTOS_ACESSOS AS PAC
ON FUN.FUN_ID = PAC.FUN_ID;

--LEFT JOIN
SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO, 
	FUN.FUN_DATA_NASCIMENTO,
	PAC.PAC_DATA_INICIAL,
	PAC.PAC_DATA_FINAL,
	CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS]
FROM FUN_FUNCIONARIOS AS FUN
LEFT JOIN PAC_PONTOS_ACESSOS AS PAC
ON FUN.FUN_ID = PAC.FUN_ID
WHERE PAC.PAC_DATA_INICIAL IS NULL;

--RIGHT JOIN
SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO, 
	FUN.FUN_DATA_NASCIMENTO,
	PAC.PAC_DATA_INICIAL,
	PAC.PAC_DATA_FINAL,
	CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS]
FROM FUN_FUNCIONARIOS AS FUN
RIGHT JOIN PAC_PONTOS_ACESSOS AS PAC
ON FUN.FUN_ID = PAC.FUN_ID
