--SELECIONADO O BANCO
USE MeuRH;

GO
--FAZENDO CALCULO DE HORAS TRABALHADAS
SELECT CONVERT(TIME(0),PAC_DATA_FINAL - PAC_DATA_INICIAL) AS [HORAS TRABALHADAS]
	FROM PAC_PONTOS_ACESSOS;

--CALCULANDO HORAS TRABALHADAS DO FUNCIONARIO
SELECT DATA,
	   FUN_ID,
	   (
		FORMAT(SUM([DIFERENCIA EM SEGUNDOS]) / 3600, '00') + ':' + 
		FORMAT((SUM([DIFERENCIA EM SEGUNDOS]) % 3600)/60, '00') + ':' +
		FORMAT(((SUM([DIFERENCIA EM SEGUNDOS])%3600)%60), '00')
	   ) AS [HORAS TRABALHADAS]
FROM(
	SELECT DATEDIFF(SECOND, PAC_DATA_INICIAL, PAC_DATA_FINAL) [DIFERENCIA EM SEGUNDOS], 
		CONVERT(DATE,PAC_DATA_FINAL) AS DATA,
		FUN_ID
		FROM PAC_PONTOS_ACESSOS
	) AS DADOS_PONTO
	GROUP BY DATA, FUN_ID
	ORDER BY DATA;

--SELECIONANDO TABELA DE ACESSOS
SELECT * FROM PAC_PONTOS_ACESSOS;

--ARRUMANDO PAC DATA FINAL
UPDATE PAC_PONTOS_ACESSOS SET PAC_DATA_FINAL = '2017-02-01 12:00:00'
WHERE FUN_ID = 1

--INSERINDO DADOS 
INSERT INTO PAC_PONTOS_ACESSOS 
(PAC_DATA_INICIAL, PAC_DATA_FINAL, FUN_ID) VALUES
('2017-02-01 13:02:00', '2017-02-01 17:07:00', 1);
INSERT INTO PAC_PONTOS_ACESSOS 
(PAC_DATA_INICIAL, PAC_DATA_FINAL, FUN_ID) VALUES
('2017-02-02 07:03:00', '2017-02-02 12:20:00', 1);

--TRAZENDO OS NOMES DOS FUNCIONARIOS
SELECT DADOS_PONTO.DATA,
	   CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS [NOME FUNCIONÁRIO],
	   (
		FORMAT(SUM([DIFERENCIA EM SEGUNDOS]) / 3600, '00') + ':' + 
		FORMAT((SUM([DIFERENCIA EM SEGUNDOS]) % 3600)/60, '00') + ':' +
		FORMAT(((SUM([DIFERENCIA EM SEGUNDOS])%3600)%60), '00')
	   ) AS [HORAS TRABALHADAS]
FROM(
	SELECT DATEDIFF(SECOND, PAC_DATA_INICIAL, PAC_DATA_FINAL) [DIFERENCIA EM SEGUNDOS], 
		CONVERT(DATE,PAC_DATA_FINAL) AS DATA,
		FUN_ID
		FROM PAC_PONTOS_ACESSOS
	) AS DADOS_PONTO
	INNER JOIN FUN_FUNCIONARIOS AS FUN
	ON DADOS_PONTO.FUN_ID = FUN.FUN_ID
	GROUP BY DADOS_PONTO.DATA, CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME)
	ORDER BY DADOS_PONTO.DATA;