--Chamando o banco MeuRH
USE [MeuRH];

GO

--Inserindo dados na tabela de funcionários
INSERT INTO  [MeuRH].[dbo].[FUN_FUNCIONARIOS](FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO, FUN_OBSERVACOES) 
VALUES ('JOÃO', 'DA SILVA', '1980-02-15', 'OBSERVAÇÃO DO FUNCIONÁRIO');

GO

--INSERINDO MAIS DE UM VALOR
INSERT INTO FUN_FUNCIONARIOS (FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO, FUN_OBSERVACOES)
VALUES 
('MARIA', 'DE SOUZA', '1990-07-03', NULL),
('JOSÉ' , 'ALENCAR' , '1968-12-05', NULL);

--SELECIONANDO OS DADOS
SELECT * FROM FUN_FUNCIONARIOS;

--SELECIONANDO ALGUNS CAMPOS
SELECT FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

--SELECIONANDO COLUNAS CONCATENADAS
SELECT FUN_NOME + ' ' + FUN_SOBRENOME AS FUN_NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

--SELECIONANDO COLUNAS CONCATENADAS COM TIPOS DE DADOS DIFERENTES
SELECT FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(FUN_DATA_NASCIMENTO AS VARCHAR) AS FUN_NOME_COMPLETO, 
FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

--UTILIZANDO A FUNÇÃO CONCAT
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS FUN_NOME_COMPLETO , FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

--VERIFICANDO O TIPO DE DADO DA SAIDA
SELECT TOP 1 SQL_VARIANT_PROPERTY(FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(ISNULL(FUN_OBSERVACOES, '') AS VARCHAR), 'BaseType')
AS NOME_COMPLETO
, FUN_DATA_NASCIMENTO
FROM FUN_FUNCIONARIOS;

--VERIFICANDO O TIPO DE DADO DA SAIDA DO CONCAT
SELECT TOP 1 SQL_VARIANT_PROPERTY(CONCAT(FUN_NOME, ' ', FUN_SOBRENOME), 'BaseType') AS FUN_NOME_COMPLETO , FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

--SELECIONANDO TODOS OS FUNCIONÁRIOS NASCIDO EM 1980 E MES DE AGOSTO
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS [NOME COMPLETO]
, FUN_DATA_NASCIMENTO
FROM FUN_FUNCIONARIOS
WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980 AND MONTH(FUN_DATA_NASCIMENTO) = 02;

--SELECIONANDO TODOS OS FUNCIONÁRIOS NASCIDO EM 1980 E ENTRE OS MESES 2 A 8
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS [NOME COMPLETO]
, FUN_DATA_NASCIMENTO
FROM FUN_FUNCIONARIOS
WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980 AND MONTH(FUN_DATA_NASCIMENTO) BETWEEN 02 AND 08;

--SELECIONANDO TODOS OS FUNCIONÁRIOS COM MAIS DE 25 ANOS
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS [NOME COMPLETO]
, FUN_DATA_NASCIMENTO
FROM FUN_FUNCIONARIOS
WHERE DATEDIFF(YEAR, FUN_DATA_NASCIMENTO, GETDATE()) >= 25;

SELECT * FROM FUN_FUNCIONARIOS;

--TRAZENDO FUNCIONÁRIOS QUE POSSUEM VALORES NULOS
SELECT FUN_NOME, FUN_SOBRENOME
FROM FUN_FUNCIONARIOS
WHERE FUN_OBSERVACOES IS NULL;

--TRAZENDO FUNCIONÁRIOS QUE NÃO POSSUEM VALORES NULOS
SELECT FUN_NOME, FUN_SOBRENOME
FROM FUN_FUNCIONARIOS
WHERE FUN_OBSERVACOES IS NOT NULL;

SELECT * FROM FUN_FUNCIONARIOS;

--SELECIONANDO FUNCIONÁRIOS PELA COLLATE
SELECT * FROM FUN_FUNCIONARIOS
WHERE FUN_NOME = 'JOÃO' COLLATE LATIN1_GENERAL_CI_AI;