--CRIANDO NOVS CAMPOS NA TABELA

--SELECIONANDO O BANCO
USE MeuRH;

GO

--INSERINDO NOVO CAMPO NA TABELA FUNCIONÁRIOS
ALTER TABLE FUN_FUNCIONARIOS 
	ADD FUN_CPF CHAR(11) NOT NULL DEFAULT '-';

SELECT * FROM FUN_FUNCIONARIOS;

--ATUALIZANDO OS CPF'S DOS FUNCIONARIOS
UPDATE FUN_FUNCIONARIOS
	SET FUN_CPF = '07736845069'
	WHERE FUN_ID = 1;

UPDATE FUN_FUNCIONARIOS
	SET FUN_CPF = '24956161000'
	WHERE FUN_ID = 4;

UPDATE FUN_FUNCIONARIOS
	SET FUN_CPF = '25198272035'
	WHERE FUN_ID = 5;

--CRIANDO UMA CONSTRAINT DE UNIQUE
ALTER TABLE FUN_FUNCIONARIOS
	ADD CONSTRAINT UC__FUN_FUNCIONARIOS_FUN_CPF UNIQUE NONCLUSTERED (FUN_CPF);

--INSERINDO VALORES PARA TESTAR A UNIQUE
INSERT INTO FUN_FUNCIONARIOS 
(FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO, FUN_OBSERVACOES, FUN_CPF) VALUES
('TREINAWEB', 'CURSOS', '2007-01-01', NULL, '25198272035')