--SELECIONANDO O BANCO
USE MeuRH;

GO

--SELECIONANDO TABELA
SELECT * FROM FUN_FUNCIONARIOS;

--SELECIONANDO TODOS OS REGISTROS DA TABELA
SELECT COUNT(*) FROM FUN_FUNCIONARIOS;

--SELECIONANDO POR FUN_ID
SELECT COUNT(FUN_ID) AS [TOTAL DE FUNCIONARIOS] FROM FUN_FUNCIONARIOS;

--SELECIONANDO A CONTAGEM CONVERTENDO O TIPO DE DADOS
SELECT COUNT(CONVERT(VARCHAR, FUN_OBSERVACOES)) AS OBSERVACOES FROM FUN_FUNCIONARIOS;

--SELECIONANDO O FUNCIONARIO MAIS VELHO
SELECT MIN(FUN_DATA_NASCIMENTO) FROM FUN_FUNCIONARIOS;

--SELECIONANDO O FUNCIONARIO MAIS NOVO
SELECT MAX(FUN_DATA_NASCIMENTO) FROM FUN_FUNCIONARIOS;

--SELECIONANDO O NOME E SOBRENOME DO FUNCIONARIO MAIS NOVO
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS [NOME COMPLETO], 
	FUN_CPF,
	FUN_DATA_NASCIMENTO  
	FROM FUN_FUNCIONARIOS
WHERE FUN_DATA_NASCIMENTO = (SELECT MAX(FUN_DATA_NASCIMENTO) FROM FUN_FUNCIONARIOS);

--SELECIONANDO OS FUNCIONARIOS PELO DEPARTAMENTO
SELECT DEP_NOME, COUNT(*) AS QTD
FROM DEP_DEPARTAMENTOS DEP
INNER JOIN FUN_FUNCIONARIOS FUN
ON DEP.DEP_ID = FUN.DEP_ID
GROUP BY DEP_NOME;

--ADICIONANDO UMA NOVA COLUNA EM FUN_FUNCIONARIOS
ALTER TABLE FUN_FUNCIONARIOS
ADD FUN_SALARIO MONEY NOT NULL DEFAULT 0;

--ATULIZANDO OS VALORES DOS SALARIOS
UPDATE FUN_FUNCIONARIOS SET FUN_SALARIO = 1000 
WHERE FUN_ID = 1;

UPDATE FUN_FUNCIONARIOS SET FUN_SALARIO = 1700
WHERE FUN_ID = 4;

UPDATE FUN_FUNCIONARIOS SET FUN_SALARIO = 5000
WHERE FUN_ID = 5 

--SOMANDO OS VALORES DOS SALARIOS
SELECT SUM(FUN_SALARIO) AS [TOTAL DE SALARIOS R$] FROM FUN_FUNCIONARIOS;

--SOMANDO SALARIOS POR DEPARTAMENTOS
SELECT DEP_NOME, SUM(FUN.FUN_SALARIO) AS [SALARIO TOTAL]
FROM  DEP_DEPARTAMENTOS DEP
INNER JOIN FUN_FUNCIONARIOS FUN
ON DEP.DEP_ID = FUN.DEP_ID
GROUP BY DEP_NOME

--FAZENDO A MEDIA DOS DEPARTAMENTOS
SELECT DEP_NOME, AVG(FUN.FUN_SALARIO) AS [SALARIO MÉDIO]
FROM  DEP_DEPARTAMENTOS DEP
INNER JOIN FUN_FUNCIONARIOS FUN
ON DEP.DEP_ID = FUN.DEP_ID
GROUP BY DEP_NOME